"""
SIUnitConversion.py

Provides SI defined unit conversion factors (in `conversion_factors` dictionary)
and a general converter function (`convert()`) to use them.
The conversion factors used are defined in [Appendix B.9.](http://www.nist.gov/pml/pubs/sp811/appenb9.cfm)
of the [NIST Guide to the SI](http://www.nist.gov/pml/pubs/sp811/).

project    : SI-Unit-Conversion
version    : 0.1.1
status     : development
modifydate : 2016-07-10 07:47:00 -0700
createdate : 2016-07-09 07:39:00 -0700
website    : https://github.com/tmthydvnprt/SI-Unit-Conversion
author     : tmthydvnprt
email      : tim@tmthydvnprt.com
maintainer : tmthydvnprt
license    : MIT
copyright  : Copyright 2016, tmthydvnprt
credits    : http://www.nist.gov/pml/pubs/sp811/

"""

# SI Unit Conversion Factors as defined in Appendix B.9. of the "NIST Guide to the SI"
# Reference: http://www.nist.gov/pml/pubs/sp811/appenb9.cfm
conversion_factors = {
    # ACCELERATION
    'gn2mps2'                   : 9.80665e+00,   # acceleration of free fall, standard (gn) to meter per second squared (m/s2)
    'ftps22mps2'                : 3.048e-01,     # foot per second squared (ft/s2) to meter per second squared (m/s2)
    'Gal2mps2'                  : 1.0e-02,       # gal (Gal) to meter per second squared (m/s2)
    'inps22mps2'                : 2.54e-02,      # inch per second squared (in/s2) to meter per second squared (m/s2)
    # ANGLE
    'deg2rad'                   : 1.745329e-02,  # degree (deg) to radian (rad)
    'gon2rad'                   : 1.570796e-02,  # gon (also called grade) (gon) to radian (rad)
    'gon2deg'                   : 9.0e-01,       # gon (also called grade) (gon) to degree (deg)
    'mil2rad'                   : 9.817477e-04,  # mil (mil) to radian (rad)
    'mil2deg'                   : 5.625e-02,     # mil (mil) to degree (deg)
    'min2rad'                   : 2.908882e-04,  # minute (min) to radian (rad)
    'r2rad'                     : 6.283185e+00,  # revolution (r) to radian (rad)
    's2rad'                     : 4.848137e-06,  # second (s) to radian (rad)
    # AREA AND SECOND MOMENT OF AREA
    'US_srvy_ft_acre2m2'        : 4.046873e+03,  # acre (U.S. survey foot acre) to square meter (m2)
    'a2m2'                      : 1.0e+02,       # are (a) to square meter (m2)
    'b2m2'                      : 1.0e-28,       # barn (b) to square meter (m2)
    'mil2m2'                    : 5.067075e-10,  # circular mil (mil) to square meter (m2)
    'mil2mm2'                   : 5.067075e-04,  # circular mil (mil) to square millimeter (mm2)
    'ft42m4'                    : 8.630975e-03,  # foot to the fourth power (ft4) to meter to the fourth power (m4)
    'ha2m2'                     : 1.0e+04,       # hectare (ha) to square meter (m2)
    'in42m4'                    : 4.162314e-07,  # inch to the fourth power (in4) to meter to the fourth power (m4)
    'ft22m2'                    : 9.290304e-02,  # square foot (ft2) to square meter (m2)
    'in22m2'                    : 6.4516e-04,    # square inch (in2) to square meter (m2)
    'in22cm2'                   : 6.4516e+00,    # square inch (in2) to square centimeter (cm2)
    'mi22m2'                    : 2.589988e+06,  # square mile (mi2) to square meter (m2)
    'mi22km2'                   : 2.589988e+00,  # square mile (mi2) to square kilometer (km2)
    'US_srvy_ft_mi22m2'         : 2.589998e+06,  # square mile (U.S. survey foot mi2) to square meter (m2)
    'US_srvy_ft_mi22km2'        : 2.589998e+00,  # square mile (U.S. survey foot mi2) to square kilometer (km2)
    'yd22m2'                    : 8.361274e-01,  # square yard (yd2) to square meter (m2)
    # CAPACITY (see VOLUME)
    # DENSITY (that is, MASS DENSITY - see MASS DIVIDED BY VOLUME)
    # ELECTRICITY and MAGNETISM
    'abampere2A'                : 1.0e+01,       # abampere (abampere) to ampere (A)
    'abcoulomb2C'               : 1.0e+01,       # abcoulomb (abcoulomb) to coulomb (C)
    'abfarad2F'                 : 1.0e+09,       # abfarad (abfarad) to farad (F)
    'abhenry2H'                 : 1.0e-09,       # abhenry (abhenry) to henry (H)
    'abmho2S'                   : 1.0e+09,       # abmho (abmho) to siemens (S)
    'abohm2ohm'                 : 1.0e-09,       # abohm (abohm) to ohm (ohm)
    'abvolt2V'                  : 1.0e-08,       # abvolt (abvolt) to volt (V)
    'Ah2C'                      : 3.6e+03,       # ampere hour (A h) to coulomb (C)
    'Bi2A'                      : 1.0e+01,       # biot (Bi) to ampere (A)
    'abfarad2F'                 : 1.0e+09,       # EMU of capacitance (abfarad) to farad (F)
    'abampere2A'                : 1.0e+01,       # EMU of current (abampere) to ampere (A)
    'abvolt2V'                  : 1.0e-08,       # EMU of electric potential (abvolt) to volt (V) (V)
    'abhenry2H'                 : 1.0e-09,       # EMU of inductance (abhenry) to henry (H)
    'abohm2ohm'                 : 1.0e-09,       # EMU of resistance (abohm) to ohm (ohm)
    'statfarad2F'               : 1.112650e-12,  # ESU of capacitance (statfarad) to farad (F)
    'statampere2A'              : 3.335641e-10,  # ESU of current (statampere) to ampere (A)
    'statvolt2V'                : 2.997925e+02,  # ESU of electric potential (statvolt) to volt (V) (V)
    'stathenry2H'               : 8.987552e+11,  # ESU of inductance (stathenry) to henry (H)
    'statohm2ohm'               : 8.987552e+11,  # ESU of resistance (statohm) to ohm (ohm)
    'faraday2C'                 : 9.648531e+04,  # faraday (based on carbon 12) (faraday) to coulomb (C)
    'Fr2C'                      : 3.335641e-10,  # franklin (Fr) to coulomb (C)
    'gamma2T'                   : 1.0e-09,       # gamma (gamma) to tesla (T)
    'Gs2T'                      : 1.0e-04,       # gauss (Gs) to tesla (T)
    'Gi2A'                      : 7.957747e-01,  # gilbert (Gi) to ampere (A)
    'Mx2Wb'                     : 1.0e-08,       # maxwell (Mx) to weber (Wb)
    'mho2S'                     : 1.0e+00,       # mho (mho) to siemens (S)
    'Oe2Apm'                    : 7.957747e+01,  # oersted (Oe) to ampere per meter (A/m)
    'ohmcm2ohmm'                : 1.0e-02,       # ohm centimeter (ohm cm) to ohm meter (ohm m)
    'milpft2ohmm'               : 1.662426e-09,  # ohm circular-mil (mil) per foot ( mil/ft) to ohm meter (ohm m)
    'milpft2ohmmm2pm'           : 1.662426e-03,  # ohm circular-mil (mil) per foot ( mil/ft) to ohm square millimeter per meter (ohm mm2/m)
    'statampere2A'              : 3.335641e-10,  # statampere (statampere) to ampere (A)
    'statcoulomb2C'             : 3.335641e-10,  # statcoulomb (statcoulomb) to coulomb (C)
    'statfarad2F'               : 1.112650e-12,  # statfarad (statfarad) to farad (F)
    'stathenry2H'               : 8.987552e+11,  # stathenry (stathenry) to henry (H)
    'statmho2S'                 : 1.112650e-12,  # statmho (statmho) to siemens (S)
    'statohm2ohm'               : 8.987552e+11,  # statohm (statohm) to ohm (ohm)
    'statvolt2V'                : 2.997925e+02,  # statvolt (statvolt) to volt (V) (V)
    'unitpole2Wb'               : 1.256637e-07,  # unit pole (unit pole) to weber (Wb)
    # ENERGY (includes WORK)
    'BtuIT2J'                   : 1.055056e+03,  # British thermal unitIT (BtuIT) to joule (J)
    'Btuth2J'                   : 1.054350e+03,  # British thermal unitth (Btuth) to joule (J)
    'Btumean2J'                 : 1.05587e+03,   # British thermal unit (Btu mean) to joule (J)
    'Btu39degF2J'               : 1.05967e+03,   # British thermal unit (Btu 39 degF) to joule (J)
    'Btu59degF2J'               : 1.05480e+03,   # British thermal unit (Btu 59 degF) to joule (J)
    'Btu60degF2J'               : 1.05468e+03,   # British thermal unit (Btu 60 degF) to joule (J)
    'calIT2J'                   : 4.1868e+00,    # calorieIT (calIT) to joule (J)
    'calth2J'                   : 4.184e+00,     # calorieth (calth) to joule (J)
    'cal2J'                     : 4.19002e+00,   # calorie (mean) (cal) to joule (J)
    'cal152J'                   : 4.18580e+00,   # calorie (15 degC) (cal15) to joule (J)
    'cal202J'                   : 4.18190e+00,   # calorie (20 degC) (cal20) to joule (J)
    'nutritioncalorieITkg2J'    : 4.1868e+03,    # calorieIT, kilogram (nutrition calorieIT kg) to joule (J)
    'nutritioncaloriethkg2J'    : 4.184e+03,     # calorieth, kilogram (nutrition calorieth kg) to joule (J)
    'nutritioncaloriemeankg2J'  : 4.19002e+03,   # calorie (mean), kilogram (nutrition calorie mean kg) to joule (J)
    'eV2J'                      : 1.602177e-19,  # electronvolt (eV) to joule (J)
    'erg2J'                     : 1.0e-07,       # erg (erg) to joule (J)
    'footpoundal2J'             : 4.214011e-02,  # foot poundal (foot poundal) to joule (J)
    'ftlbf2J'                   : 1.355818e+00,  # foot pound-force (ft lbf) to joule (J)
    'kcalIT2J'                  : 4.1868e+03,    # kilocalorieIT (kcalIT) to joule (J)
    'kcalth2J'                  : 4.184e+03,     # kilocalorieth (kcalth) to joule (J)
    'kcal2J'                    : 4.19002e+03,   # kilocalorie (mean) (kcal) to joule (J)
    'kWh2J'                     : 3.6e+06,       # kilowatt hour (kW h) to joule (J)
    'kWh2MJ'                    : 3.6e+00,       # kilowatt hour (kW h) to megajoule (MJ)
    'BtuIT10152J'               : 1.055056e+18,  # quad (BtuIT 1015) to joule (J)
    'EC2J_therm'                : 1.05506e+08,   # therm (EC) to joule (J_therm)
    'US_2J_therm'               : 1.054804e+08,  # therm (U.S.) to joule (J_therm)
    'tonTNT2J'                  : 4.184e+09,     # ton of TNT (tonTNT) to joule (J)
    'Wh2J'                      : 3.6e+03,       # watt hour (W h) to joule (J)
    'Ws2J'                      : 1.0e+00,       # watt second (W s) to joule (J)
    # ENERGY DIVIDED BY AREA TIME
    'ergpcm2ps2Wpm2'            : 1.0e-03,       # erg per square centimeter second (erg/cm2/s) to watt per square meter (W/m2)
    'Wpcm22Wpm2'                : 1.0e+04,       # watt per square centimeter (W/cm2) to watt per square meter (W/m2)
    'Wpin22Wpm2'                : 1.550003e+03,  # watt per square inch (W/in2) to watt per square meter (W/m2)
    # FLOW (see MASS DIVIDED BY TIME or VOLUME DIVIDED BY TIME)
    # FORCE
    'dyn2N'                     : 1.0e-05,       # dyne (dyn) to newton (N)
    'kgf2N'                     : 9.80665e+00,   # kilogram-force (kgf) to newton (N)
    'kp2N'                      : 9.80665e+00,   # kilopond (kilogram-force) (kp) to newton (N)
    'kip2N'                     : 4.448222e+03,  # kip (1 kip equals 1000 lbf) (kip) to newton (N)
    'kip2kN'                    : 4.448222e+00,  # kip (1 kip equals 1000 lbf) (kip) to kilonewton (kN)
    'ozf2N'                     : 2.780139e-01,  # ounce (avoirdupois)-force (ozf) to newton (N)
    'poundal2N'                 : 1.382550e-01,  # poundal (poundal) to newton (N)
    'lbf2N'                     : 4.448222e+00,  # pound-force (lbf) to newton (N)
    'lbfplb2Npkg'               : 9.80665e+00,   # pound-force per pound (thrust to mass ratio) (lbf/lb) to newton per kilogram (N/kg)
    'tonf2N'                    : 8.896443e+03,  # ton-force (ton f) to newton (N)
    'tonf2kN'                   : 8.896443e+00,  # ton-force (ton f) to kilonewton (kN)
    # FORCE DIVIDED BY AREA (see PRESSURE)
    # FORCE DIVIDED BY LENGTH
    'lbfpft2Npm'                : 1.459390e+01,  # pound-force per foot (lbf/ft) to newton per meter (N/m)
    'lbfpin2Npm'                : 1.751268e+02,  # pound-force per inch (lbf/in) to newton per meter (N/m)
    # HEAT
    # Available Energy
    'BtuITpft32Jpm3'            : 3.725895e+04,  # British thermal unitIT per cubic foot (BtuIT/ft3) to joule per cubic meter (J/m3)
    'Btuthpft32Jpm3'            : 3.723403e+04,  # British thermal unitth per cubic foot (Btuth/ft3) to joule per cubic meter (J/m3)
    'BtuITplb2Jpkg'             : 2.326e+03,     # British thermal unitIT per pound (BtuIT/lb) to joule per kilogram (J/kg)
    'Btuthplb2Jpkg'             : 2.324444e+03,  # British thermal unitth per pound (Btuth/lb) to joule per kilogram (J/kg)
    'calITpg2Jpkg'              : 4.1868e+03,    # calorieIT per gram (calIT/g) to joule per kilogram (J/kg)
    'calthpg2Jpkg'              : 4.184e+03,     # calorieth per gram (calth/g) to joule per kilogram (J/kg)
    # Coefficient of Heat Transfer
    'BtuITphp3pdegF2Wpm2pK'     : 5.678263e+00,  # British thermal unitIT per hour square foot degree Fahrenheit (BtuIT/h/3/degF) to watt per square meter kelvin (W/m2/K)
    'Btuthphp3pdegF2Wpm2pK'     : 5.674466e+00,  # British thermal unitth per hour square foot degree Fahrenheit (Btuth/h/3/degF) to watt per square meter kelvin (W/m2/K)
    'BtuITpsp3pdegF2Wpm2pK'     : 2.044175e+04,  # British thermal unitIT per second square foot degree Fahrenheit (BtuIT/s/3/degF) to watt per square meter kelvin (W/m2/K)
    'Btuthpsp3pdegF2Wpm2pK'     : 2.042808e+04,  # British thermal unitth per second square foot degree Fahrenheit (Btuth/s/3/degF) to watt per square meter kelvin (W/m2/K)
    # Density of Heat
    'BtuITpft22Jpm2'            : 1.135653e+04,  # British thermal unitIT per square foot (BtuIT/ft2) to joule per square meter (J/m2)
    'Btuthpft22Jpm2'            : 1.134893e+04,  # British thermal unitth per square foot (Btuth/ft2) to joule per square meter (J/m2)
    'calthpcm22Jpm2'            : 4.184e+04,     # calorieth per square centimeter (calth/cm2) to joule per square meter (J/m2)
    'calthpcm22Jpm2'            : 4.184e+04,     # langley (calth/cm2) to joule per square meter (J/m2)
    # Density of Heat Flow Rate
    'BtuITpft2ph2Wpm2'          : 3.154591e+00,  # British thermal unitIT per square foot hour (BtuIT/ft2/h) to watt per square meter (W/m2)
    'Btuthpft2ph2Wpm2'          : 3.152481e+00,  # British thermal unitth per square foot hour (Btuth/ft2/h) to watt per square meter (W/m2)
    'Btuthpft2pmin2Wpm2'        : 1.891489e+02,  # British thermal unitth per square foot minute (Btuth/ft2/min) to watt per square meter (W/m2)
    'BtuITpft2ps2Wpm2'          : 1.135653e+04,  # British thermal unitIT per square foot second (BtuIT/ft2/s) to watt per square meter (W/m2)
    'Btuthpft2ps2Wpm2'          : 1.134893e+04,  # British thermal unitth per square foot second (Btuth/ft2/s) to watt per square meter (W/m2)
    'Btuthpinp3ps2Wpm2'         : 1.634246e+06,  # British thermal unitth per square inch second (Btuth/in/3/s) to watt per square meter (W/m2)
    'calthpcm2pmin2Wpm2'        : 6.973333e+02,  # calorieth per square centimeter minute (calth/cm2/min) to watt per square meter (W/m2)
    'calthpcm2ps2Wpm2'          : 4.184e+04,     # calorieth per square centimeter second (calth/cm2/s) to watt per square meter (W/m2)
    # Fuel Consumption
    'galphpph2m3pJ'             : 1.410089e-09,  # gallon (U.S.) per horsepower hour (gal/hp/h) to cubic meter per joule (m3/J)
    'galphpph2LpJ'              : 1.410089e-06,  # gallon (U.S.) per horsepower hour (gal/hp/h) to liter per joule (L/J)
    'US_mipgal2mpm3'            : 4.251437e+05,  # mile per gallon (U.S. mi/gal) to meter per cubic meter (m/m3)
    'US_mipgal2kmpL'            : 4.251437e-01,  # mile per gallon (U.S. mi/gal) to kilometer per liter (km/L)
    'lbphpph2kgpJ'              : 1.689659e-07,  # pound per horsepower hour (lb/hp/h) to kilogram per joule (kg/J)
    # Heat Capacity and Entropy
    'BtuITpdegF2JpK'            : 1.899101e+03,  # British thermal unitIT per degree Fahrenheit (BtuIT/degF) to joule per kelvin (J/K)
    'BtuthpdegF2JpK'            : 1.897830e+03,  # British thermal unitth per degree Fahrenheit (Btuth/degF) to joule per kelvin (J/K)
    'BtuITpdegR2JpK'            : 1.899101e+03,  # British thermal unitIT per degree Rankine (BtuIT/degR) to joule per kelvin (J/K)
    'BtuthpdegR2JpK'            : 1.897830e+03,  # British thermal unitth per degree Rankine (Btuth/degR) to joule per kelvin (J/K)
    # Heat Flow Rate
    'BtuITph2W'                 : 2.930711e-01,  # British thermal unitIT per hour (BtuIT/h) to watt (W)
    'Btuthph2W'                 : 2.928751e-01,  # British thermal unitth per hour (Btuth/h) to watt (W)
    'Btuthpmin2W'               : 1.757250e+01,  # British thermal unitth per minute (Btuth/min) to watt (W)
    'BtuITps2W'                 : 1.055056e+03,  # British thermal unitIT per second (BtuIT/s) to watt (W)
    'Btuthps2W'                 : 1.054350e+03,  # British thermal unitth per second (Btuth/s) to watt (W)
    'calthpmin2W'               : 6.973333e-02,  # calorieth per minute (calth/min) to watt (W)
    'calthps2W'                 : 4.184e+00,     # calorieth per second (calth/s) to watt (W)
    'kcalthpmin2W'              : 6.973333e+01,  # kilocalorieth per minute (kcalth/min) to watt (W)
    'kcalthps2W'                : 4.184e+03,     # kilocalorieth per second (kcalth/s) to watt (W)
    'tonREFRIG2W'               : 3.516853e+03,  # ton of refrigeration (12 000 BtuIT/h) (tonREFRIG) to watt (W)
    # Specific Heat Capacity and Specific Entropy
    'BtuITplbpdegF2JpkgpK'      : 4.1868e+03,    # British thermal unitIT per pound degree Fahrenheit (BtuIT/lb/degF) to joule per kilogram kelvin (J/kg/K)
    'BtuthplbpdegF2JpkgpK'      : 4.184e+03,     # British thermal unitth per pound degree Fahrenheit (Btuth/lb/degF) to joule per kilogram kelvin (J/kg/K)
    'BtuITplbpdegR2JpkgpK'      : 4.1868e+03,    # British thermal unitIT per pound degree Rankine (BtuIT/lb/degR) to joule per kilogram kelvin (J/kg/K)
    'BtuthplbpdegR2JpkgpK'      : 4.184e+03,     # British thermal unitth per pound degree Rankine (Btuth/lb/degR) to joule per kilogram kelvin (J/kg/K)
    'calITpgpdegC2JpkgpK'       : 4.1868e+03,    # calorieIT per gram degree Celsius (calIT/g/degC) to joule per kilogram kelvin (J/kg/K)
    'calthpgpdegC2JpkgpK'       : 4.184e+03,     # calorieth per gram degree Celsius (calth/g/degC) to joule per kilogram kelvin (J/kg/K)
    'calITpgpK2JpkgpK'          : 4.1868e+03,    # calorieIT per gram kelvin (calIT/g/K) to joule per kilogram kelvin (J/kg/K)
    'calthpgpK2JpkgpK'          : 4.184e+03,     # calorieth per gram kelvin (calth/g/K) to joule per kilogram kelvin (J/kg/K)
    # Thermal Conductivity
    'BtuITftphpft2pdegF2WpmpK'  : 1.730735e+00,  # Britsh thermal unitIT foot per hour square foot degree Fahrenheit (BtuIT ft/h/ft2/degF) to watt per meter kelvin (W/m/K)
    'Btuthftphpft2pdegF2WpmpK'  : 1.729577e+00,  # Britsh thermal unitth foot per hour square foot degree Fahrenheit (Btuth ft/h/ft2/degF) to watt per meter kelvin (W/m/K)
    'BtuITinphpft2pdegF2WpmpK'  : 1.442279e-01,  # Britsh thermal unitIT inch per hour square foot degree Fahrenheit (BtuIT in/h/ft2/degF) to watt per meter kelvin (W/m/K)
    'Btuthinphpft2pdegF2WpmpK'  : 1.441314e-01,  # Britsh thermal unitth inch per hour square foot degree Fahrenheit (Btuth in/h/ft2/degF) to watt per meter kelvin (W/m/K)
    'BtuITinpspft2pdegF2WpmpK'  : 5.192204e+02,  # Britsh thermal unitIT inch per second square foot degree Fahrenheit (BtuIT in/s/ft2/degF) to watt per meter kelvin (W/m/K)
    'Btuthinpspft2pdegF2WpmpK'  : 5.188732e+02,  # Britsh thermal unitth inch per second square foot degree Fahrenheit (Btuth in/s/ft2/degF) to watt per meter kelvin (W/m/K)
    'calthpcmp3pdegC2WpmpK'     : 4.184e+02,     # calorieth per centimeter second degree Celsius (calth/cm/3/degC) to watt per meter kelvin (W/m/K)
    # Thermal Diffusivity
    'ft2ph2m2ps'                : 2.58064e-05,   # square foot per hour (ft2/h) to square meter per second (m2/s)
    # Thermal Insulance
    'clo2m2KpW'                 : 1.55e-01,      # clo (clo) to square meter kelvin per watt (m2 K/W)
    'degFhft2pBtuIT2m2KpW'      : 1.761102e-01,  # degree Fahrenheit hour square foot per British thermal unitIT (degF h ft2/BtuIT) to square meter kelvin per watt (m2 K/W)
    'degFhft2pBtuth2m2KpW'      : 1.762280e-01,  # degree Fahrenheit hour square foot per British thermal unitth (degF h ft2/Btuth) to square meter kelvin per watt (m2 K/W)
    # Thermal Resistance
    'degFhpBtuIT2KpW'           : 1.895634e+00,  # degree Fahrenheit hour per British thermal unitIT (degF h/BtuIT) to kelvin per watt (K/W)
    'degFhpBtuth2KpW'           : 1.896903e+00,  # degree Fahrenheit hour per British thermal unitth (degF h/Btuth) to kelvin per watt (K/W)
    'degFspBtuIT2KpW'           : 5.265651e-04,  # degree Fahrenheit second per British thermal unitIT (degF s/BtuIT) to kelvin per watt (K/W)
    'degFspBtuth2KpW'           : 5.269175e-04,  # degree Fahrenheit second per British thermal unitth (degF s/Btuth) to kelvin per watt (K/W)
    # Thermal Resistivity
    'degFhft2pBtuITpin2mKpW'    : 6.933472e+00,  # degree Fahrenheit hour square foot per British thermal unitIT inch (degF h ft2/BtuIT/in) to meter kelvin per watt (m K/W)
    'degFhft2pBtuthpin2mKpW'    : 6.938112e+04,  # degree Fahrenheit hour square foot per British thermal unitth inch (degF h ft2/Btuth/in) to meter kelvin per watt (m K/W)
    # LENGTH
    'A2m'                       : 1.0e-10,       # angstrom (A) to meter (m)
    'A2nm'                      : 1.0e-01,       # angstrom (A) to nanometer (nm)
    'ua2m'                      : 1.495979e+11,  # astronomical unit (ua) to meter (m)
    'US_srvy_ft_ch2m'           : 2.011684e+01,  # chain (U.S. survey foot ch) to meter (m)
    'US_srvy_ft_fathom2m'       : 1.828804e+00,  # fathom (U.S. survey foot fathom) to meter (m)
    'fermi2m'                   : 1.0e-15,       # fermi (fermi) to meter (m)
    'fermi2fm'                  : 1.0e+00,       # fermi (fermi) to femtometer (fm)
    'ft2m'                      : 3.048e-01,     # foot (ft) to meter (m)
    'US_srvy_ft_ft2m'           : 3.048006e-01,  # foot (U.S. survey foot ft) to meter (m)
    'in2m'                      : 2.54e-02,      # inch (in) to meter (m)
    'in2cm'                     : 2.54e+00,      # inch (in) to centimeter (cm)
    'K2pm'                      : 1e+02,         # kayser (K) to reciprocal meter (/m)
    'lyyear2m'                  : 9.46073e+15,   # light year (ly ( (ly year) to meter (m)
    'microinch2m'               : 2.54e-08,      # microinch (microinch) to meter (m)
    'microinch2um'              : 2.54e-02,      # microinch (microinch) to micrometer (um)
    'u2m'                       : 1.0e-06,       # micron (u) to meter (m)
    'u2um'                      : 1.0e+00,       # micron (u) to micrometer (um)
    'mil2m'                     : 2.54e-05,      # mil (mil) to meter (m)
    'mil2mm'                    : 2.54e-02,      # mil (mil) to millimeter (mm)
    'mi2m'                      : 1.609344e+03,  # mile (mi) to meter (m)
    'mi2km'                     : 1.609344e+00,  # mile (mi) to kilometer (km)
    'US_srvy_ft_mi2m'           : 1.609347e+03,  # mile (U.S. survey foot mi) to meter (m)
    'US_srvy_ft_mi2km'          : 1.609347e+00,  # mile (U.S. survey foot mi) to kilometer (km)
    'NM2m'                      : 1.852e+03,     # nautical mile (NM) to meter (m)
    'pc2m'                      : 3.085678e+16,  # parsec (pc) to meter (m)
    'computerpica2m'            : 4.233333e-03,  # pica (computer) (computer pica) to meter (m)
    'computerpica2mm'           : 4.233333e+00,  # pica (computer) (computer pica) to millimeter (mm)
    'printerspica2m'            : 4.217518e-03,  # pica (printers) (printers pica) to meter (m)
    'printerspica2mm'           : 4.217518e+00,  # pica (printers) (printers pica) to millimeter (mm)
    'computerpoint2m'           : 3.527778e-04,  # point (computer) (computer point) to meter (m)
    'computerpoint2mm'          : 3.527778e-01,  # point (computer) (computer point) to millimeter (mm)
    'printerspoint2m'           : 3.514598e-04,  # point (printers) (printers point) to meter (m)
    'printerspoint2mm'          : 3.514598e-01,  # point (printers) (printers point) to millimeter (mm)
    'US_srvy_ft_rd2m'           : 5.029210e+00,  # rod (U.S. survey foot rd) to meter (m)
    'yd2m'                      : 9.144e-01,     # yard (yd) to meter (m)
    # LIGHT
    'cdpin22cdpm2'              : 1.550003e+03,  # candela per square inch (cd/in2) to candela per square meter (cd/m2)
    'footcandle2lx'             : 1.076391e+01,  # footcandle (footcandle) to lux (lx)
    'footlambert2cdpm2'         : 3.426259e+00,  # footlambert (footlambert) to candela per square meter (cd/m2)
    'lambert2cdpm2'             : 3.183099e+03,  # lambert (lambert) to candela per square meter (cd/m2)
    'lmpft22lx'                 : 1.076391e+01,  # lumen per square foot (lm/ft2) to lux (lx)
    'ph2lx'                     : 1.0e+04,       # phot (ph) to lux (lx)
    'sb2cdpm2'                  : 1.0e+04,       # stilb (sb) to candela per square meter (cd/m2)
    # MASS and MOMENT OF INERTIA
    'carat2kg'                  : 2.0e-04,       # carat (carat) to kilogram (kg)
    'carat2g'                   : 2.0e-01,       # carat (carat) to gram (g)
    'gr2kg'                     : 6.479891e-05,  # grain (gr) to kilogram (kg)
    'gr2mg'                     : 6.479891e+01,  # grain (gr) to milligram (mg)
    'hundredweightlong2kg'      : 5.080235e+01,  # hundredweight (long, 112 lb) (hundredweight long) to kilogram (kg)
    'hundredweightshort2kg'     : 4.535924e+01,  # hundredweight (short, 100 lb) (hundredweight short) to kilogram (kg)
    'kgfs2pm2kg'                : 9.80665e+00,   # kilogram-force second squared per meter (kgf s2/m) to kilogram (kg)
    'oz2kg'                     : 2.834952e-02,  # ounce (avoirdupois) (oz) to kilogram (kg)
    'oz2g'                      : 2.834952e+01,  # ounce (avoirdupois) (oz) to gram (g)
    'troyounce2kg'              : 3.110348e-02,  # ounce (troy or apothecary) (oz) (troy ounce) to kilogram (kg)
    'troyounce2g'               : 3.110348e+01,  # ounce (troy or apothecary) (oz) (troy ounce) to gram (g)
    'dwt2kg'                    : 1.555174e-03,  # pennyweight (dwt) to kilogram (kg)
    'dwt2g'                     : 1.555174e+00,  # pennyweight (dwt) to gram (g)
    'lb2kg'                     : 4.535924e-01,  # pound (avoirdupois) (lb) to kilogram (kg)
    'troypound2kg'              : 3.732417e-01,  # pound (troy or apothecary) (lb) (troy pound) to kilogram (kg)
    'lbft22kgm2'                : 4.214011e-02,  # pound foot squared (lb ft2) to kilogram meter squared (kg m2)
    'lbin22kgm2'                : 2.926397e-04,  # pound inch squared (lb in2) to kilogram meter squared (kg m2)
    'slug2kg'                   : 1.459390e+01,  # slug (slug) to kilogram (kg)
    'AT2kg'                     : 2.916667e-02,  # ton, assay (AT) to kilogram (kg)
    'AT2g'                      : 2.916667e+01,  # ton, assay (AT) to gram (g)
    'tonlong2kg'                : 1.016047e+03,  # ton, long (2240 lb) (ton long) to kilogram (kg)
    't2kg'                      : 1.0e+03,       # ton, metric (t) to kilogram (kg)
    't2kg'                      : 1.0e+03,       # tonne (called "metric ton" in U.S.) (t) to kilogram (kg)
    'tonshort2kg'               : 9.071847e+02,  # ton, short (2000 lb) (ton short) to kilogram (kg)
    # MASS DENSITY (see MASS DIVIDED BY VOLUME)
    # MASS DIVIDED BY AREA
    'ozpft22kgpm2'              : 3.051517e-01,  # ounce (avoirdupois) per square foot (oz/ft2) to kilogram per square meter (kg/m2)
    'ozpin22kgpm2'              : 4.394185e+01,  # ounce (avoirdupois) per square inch (oz/in2) to kilogram per square meter (kg/m2)
    'ozpyd22kgpm2'              : 3.390575e-02,  # ounce (avoirdupois) per square yard (oz/yd2) to kilogram per square meter (kg/m2)
    'lbpft22kgpm2'              : 4.882428e+00,  # pound per square foot (lb/ft2) to kilogram per square meter (kg/m2)
    'lbpin22kgpm2'              : 7.030696e+02,  # pound per square inch (not pound force) (lb/in2) to kilogram per square meter (kg/m2)
    # MASS DIVIDED BY CAPACITY (see MASS DIVIDED BY VOLUME)
    # MASS DIVIDED BY LENGTH
    'denier2kgpm'               : 1.111111e-07,  # denier (denier) to kilogram per meter (kg/m)
    'denier2gpm'                : 1.111111e-04,  # denier (denier) to gram per meter (g/m)
    'lbpft2kgpm'                : 1.488164e+00,  # pound per foot (lb/ft) to kilogram per meter (kg/m)
    'lbpin2kgpm'                : 1.785797e+01,  # pound per inch (lb/in) to kilogram per meter (kg/m)
    'lbpyd2kgpm'                : 4.960546e-01,  # pound per yard (lb/yd) to kilogram per meter (kg/m)
    'tex2kgpm'                  : 1.0e-06,       # tex (tex) to kilogram per meter (kg/m)
    # MASS DIVIDED BY TIME (includes FLOW)
    'lbph2kgps'                 : 1.259979e-04,  # pound per hour (lb/h) to kilogram per second (kg/s)
    'lbpmin2kgps'               : 7.559873e-03,  # pound per minute (lb/min) to kilogram per second (kg/s)
    'lbps2kgps'                 : 4.535924e-01,  # pound per second (lb/s) to kilogram per second (kg/s)
    'tonshortph2kgps'           : 2.519958e-01,  # ton, short, per hour (ton short/h) to kilogram per second (kg/s)
    # MASS DIVIDED BY VOLUME (includes MASS DENSITY and MASS CONCENTRATION)
    'US_grpgal2kgpm3'           : 1.711806e-02,  # grain per gallon (U.S. gr/gal) to kilogram per cubic meter (kg/m3)
    'US_grpgal2mgpL'            : 1.711806e+01,  # grain per gallon (U.S. gr/gal) to milligram per liter (mg/L)
    'gpcm32kgpm3'               : 1.0e+03,       # gram per cubic centimeter (g/cm3) to kilogram per cubic meter (kg/m3)
    'ozpin32kgpm3'              : 1.729994e+03,  # ounce (avoirdupois) per cubic inch (oz/in3) to kilogram per cubic meter (kg/m3)
    'UK_ozpgal2kgpm3'           : 6.236023e+00,  # ounce (avoirdupois) per gallon (U.K. oz/gal) to kilogram per cubic meter (kg/m3)
    'UK_ozpgal2gpL'             : 6.236023e+00,  # ounce (avoirdupois) per gallon (U.K. oz/gal) to gram per liter (g/L)
    'US_ozpgal2kgpm3'           : 7.489152e+00,  # ounce (avoirdupois) per gallon (U.S. oz/gal) to kilogram per cubic meter (kg/m3)
    'US_ozpgal2gpL'             : 7.489152e+00,  # ounce (avoirdupois) per gallon (U.S. oz/gal) to gram per liter (g/L)
    'lbpft32kgpm3'              : 1.601846e+01,  # pound per cubic foot (lb/ft3) to kilogram per cubic meter (kg/m3)
    'lbpin32kgpm3'              : 2.767990e+04,  # pound per cubic inch (lb/in3) to kilogram per cubic meter (kg/m3)
    'lbpyd32kgpm3'              : 5.932764e-01,  # pound per cubic yard (lb/yd3) to kilogram per cubic meter (kg/m3)
    'UK_lbpgal2kgpm3'           : 9.977637e+01,  # pound per gallon (U.K. lb/gal) to kilogram per cubic meter (kg/m3)
    'UK_lbpgal2kgpL'            : 9.977637e-02,  # pound per gallon (U.K. lb/gal) to kilogram per liter (kg/L)
    'US_lbpgal2kgpm3'           : 1.198264e+02,  # pound per gallon (U.S. lb/gal) to kilogram per cubic meter (kg/m3)
    'US_lbpgal2kgpL'            : 1.198264e-01,  # pound per gallon (U.S. lb/gal) to kilogram per liter (kg/L)
    'slugpft32kgpm3'            : 5.153788e+02,  # slug per cubic foot (slug/ft3) to kilogram per cubic meter (kg/m3)
    'tonlongpyd32kgpm3'         : 1.328939e+03,  # ton, long, per cubic yard (ton long/yd3) to kilogram per cubic meter (kg/m3)
    'tonshortpyd32kgpm3'        : 1.186553e+03,  # ton, short, per cubic yard (ton short/yd3) to kilogram per cubic meter (kg/m3)
    # MOMENT OF FORCE or TORQUE
    'dyncm2Nm'                  : 1.0e-07,       # dyne centimeter (dyn cm) to newton meter (N m)
    'kgfm2Nm'                   : 9.80665e+00,   # kilogram-force meter (kgf m) to newton meter (N m)
    'ozfin2Nm'                  : 7.061552e-03,  # ounce (avoirdupois)-force inch (ozf in) to newton meter (N m)
    'ozfin2mNm'                 : 7.061552e+00,  # ounce (avoirdupois)-force inch (ozf in) to millinewton meter (mN m)
    'lbfft2Nm'                  : 1.355818e+00,  # pound-force foot (lbf ft) to newton meter (N m)
    'lbfin2Nm'                  : 1.129848e-01,  # pound-force inch (lbf in) to newton meter (N m)
    # MOMENT OF FORCE or TORQUE, DIVIDED BY LENGTH
    'lbfftpin2Nmpm'             : 5.337866e+01,  # pound-force foot per inch (lbf ft/in) to newton meter per meter (N m/m)
    'lbfinpin2Nmpm'             : 4.448222e+00,  # pound-force inch per inch (lbf in/in) to newton meter per meter (N m/m)
    # PERMEABILITY
    'darcy2m2'                  : 9.869233e-13,  # darcy (darcy) to meter squared (m2)
    'perm0degC2kgpPap3pm2'      : 5.72135e-11,   # perm 0 degC (perm 0 degC) to kilogram per pascal second square meter (kg/Pa/3/m2)
    'perm23degC2kgpPap3pm2'     : 5.74525e-11,   # perm 23 degC (perm 23 degC) to kilogram per pascal second square meter (kg/Pa/3/m2)
    'perminch0degC2kgpPap3pm'   : 1.45322e-12,   # perm inch 0 degC (perm inch 0 degC) to kilogram per pascal second meter (kg/Pa/3/m)
    'perminch23degC2kgpPap3pm'  : 1.45929e-12,   # perm inch 23 degC (perm inch 23 degC) to kilogram per pascal second meter (kg/Pa/3/m)
    # POWER
    'ergps2W'                   : 1.0e-07,       # erg per second (erg/s) to watt (W)
    'ftlbfph2W'                 : 3.766161e-04,  # foot pound-force per hour (ft lbf/h) to watt (W)
    'ftlbfpmin2W'               : 2.259697e-02,  # foot pound-force per minute (ft lbf/min) to watt (W)
    'ftlbfps2W'                 : 1.355818e+00,  # foot pound-force per second (ft lbf/s) to watt (W)
    'hp2W'                      : 7.456999e+02,  # horsepower (550 ft lbf/s) (hp) to watt (W)
    'boilerhp2W'                : 9.80950e+03,   # horsepower (boiler hp) to watt (W)
    'electrichp2W'              : 7.46e+02,      # horsepower (electric hp) to watt (W)
    'metrichp2W'                : 7.354988e+02,  # horsepower (metric hp) to watt (W)
    'UK_hp2W'                   : 7.4570e+02,    # horsepower (U.K. hp) to watt (W)
    'waterhp2W'                 : 7.46043e+02,   # horsepower (water hp) to watt (W)
    # PRESSURE or STRESS (FORCE DIVIDED BY AREA)
    'atm2Pa'                    : 1.01325e+05,   # atmosphere, standard (atm) to pascal (Pa)
    'atm2kPa'                   : 1.01325e+02,   # atmosphere, standard (atm) to kilopascal (kPa)
    'at2Pa'                     : 9.80665e+04,   # atmosphere, technical (at) to pascal (Pa)
    'at2kPa'                    : 9.80665e+01,   # atmosphere, technical (at) to kilopascal (kPa)
    'bar2Pa'                    : 1.0e+05,       # bar (bar) to pascal (Pa)
    'bar2kPa'                   : 1.0e+02,       # bar (bar) to kilopascal (kPa)
    'cmHg0degC2Pa'              : 1.33322e+03,   # centimeter of mercury (0 degC) (cmHg 0 degC) to pascal (Pa)
    'cmHg0degC2kPa'             : 1.33322e+00,   # centimeter of mercury (0 degC) (cmHg 0 degC) to kilopascal (kPa)
    'cmHg2Pa'                   : 1.333224e+03,  # centimeter of mercury, conventional (cmHg) to pascal (Pa)
    'cmHg2kPa'                  : 1.333224e+00,  # centimeter of mercury, conventional (cmHg) to kilopascal (kPa)
    'cmH2O4degC2Pa'             : 9.80638e+01,   # centimeter of water (4 degC) (cmH2O 4 degC) to pascal (Pa)
    'cmH2O2Pa'                  : 9.80665e+01,   # centimeter of water, conventional (cmH2O) to pascal (Pa)
    'dynpcm22Pa'                : 1.0e-01,       # dyne per square centimeter (dyn/cm2) to pascal (Pa)
    'ftHg2Pa'                   : 4.063666e+04,  # foot of mercury, conventional (ftHg) to pascal (Pa)
    'ftHg2kPa'                  : 4.063666e+01,  # foot of mercury, conventional (ftHg) to kilopascal (kPa)
    'ftH2O39_2degF2Pa'          : 2.98898e+03,   # foot of water (39.2 degF) (ftH2O 39.2 degF) to pascal (Pa)
    'ftH2O39_2degF2kPa'         : 2.98898e+00,   # foot of water (39.2 degF) (ftH2O 39.2 degF) to kilopascal (kPa)
    'ftH2O2Pa'                  : 2.989067e+03,  # foot of water, conventional (ftH2O) to pascal (Pa)
    'ftH2O2kPa'                 : 2.989067e+00,  # foot of water, conventional (ftH2O) to kilopascal (kPa)
    'gfpcm22Pa'                 : 9.80665e+01,   # gram-force per square centimeter (gf/cm2) to pascal (Pa)
    'inHg32degF2Pa'             : 3.38638e+03,   # inch of mercury (32 degF) (inHg 32 degF) to pascal (Pa)
    'inHg32degF2kPa'            : 3.38638e+00,   # inch of mercury (32 degF) (inHg 32 degF) to kilopascal (kPa)
    'inHg60degF2Pa'             : 3.37685e+03,   # inch of mercury (60 degF) (inHg 60 degF) to pascal (Pa)
    'inHg60degF2kPa'            : 3.37685e+00,   # inch of mercury (60 degF) (inHg 60 degF) to kilopascal (kPa)
    'inHg2Pa'                   : 3.386389e+03,  # inch of mercury, conventional (inHg) to pascal (Pa)
    'inHg2kPa'                  : 3.386389e+00,  # inch of mercury, conventional (inHg) to kilopascal (kPa)
    'inH2O39_2degF2Pa'          : 2.49082e+02,   # inch of water (39.2 degF) (inH2O 39.2 degF) to pascal (Pa)
    'inH2O60degF2Pa'            : 2.4884e+02,    # inch of water (60 degF) (inH2O 60 degF) to pascal (Pa)
    'inH2O2Pa'                  : 2.490889e+02,  # inch of water, conventional (inH2O) to pascal (Pa)
    'kgfpcm22Pa'                : 9.80665e+04,   # kilogram-force per square centimeter (kgf/cm2) to pascal (Pa)
    'kgfpcm22kPa'               : 9.80665e+01,   # kilogram-force per square centimeter (kgf/cm2) to kilopascal (kPa)
    'kgfpm22Pa'                 : 9.80665e+00,   # kilogram-force per square meter (kgf/m2) to pascal (Pa)
    'kgfpmm22Pa'                : 9.80665e+06,   # kilogram-force per square millimeter (kgf/mm2) to pascal (Pa)
    'kgfpmm22MPa'               : 9.80665e+00,   # kilogram-force per square millimeter (kgf/mm2) to megapascal (MPa)
    'kippin22Pa'                : 6.894757e+06,  # kip per square inch (ksi) (kip/in2) to pascal (Pa)
    'kippin22kPa'               : 6.894757e+03,  # kip per square inch (ksi) (kip/in2) to kilopascal (kPa)
    'mbar2Pa'                   : 1.0e+02,       # millibar (mbar) to pascal (Pa)
    'mbar2kPa'                  : 1.0e-01,       # millibar (mbar) to kilopascal (kPa)
    'mmHg2Pa'                   : 1.333224e+02,  # millimeter of mercury, conventional (mmHg) to pascal (Pa)
    'mmH2O2Pa'                  : 9.80665e+00,   # millimeter of water, conventional (mmH2O) to pascal (Pa)
    'poundalpft22Pa'            : 1.488164e+00,  # poundal per square foot (poundal / ft2) to pascal (Pa)
    'lbfpft22Pa'                : 4.788026e+01,  # pound-force per square foot (lbf/ft2) to pascal (Pa)
    'lbfpin22Pa'                : 6.894757e+03,  # pound-force per square inch (psi) (lbf/in2) to pascal (Pa)
    'lbfpin22kPa'               : 6.894757e+00,  # pound-force per square inch (psi) (lbf/in2) to kilopascal (kPa)
    'lbfpin22Pa'                : 6.894757e+03,  # psi (pound-force per square inch) (lbf/in2) to pascal (Pa)
    'lbfpin22kPa'               : 6.894757e+00,  # psi (pound-force per square inch) (lbf/in2) to kilopascal (kPa)
    'Torr2Pa'                   : 1.333224e+02,  # torr (Torr) to pascal (Pa)
    # RADIOLOGY
    'Ci2Bq'                     : 3.7e+10,       # curie (Ci) to becquerel (Bq)
    'rad2Gy'                    : 1.0e-02,       # rad (absorbed dose) (rad) to gray (Gy)
    'rem2Sv'                    : 1.0e-02,       # rem (rem) to sievert (Sv)
    'R2Cpkg'                    : 2.58e-04,      # roentgen (R) to coulomb per kilogram (C/kg)
    # SPEED (see VELOCITY)
    # STRESS (see PRESSURE)
    # TEMPERATURE
    # TEMPERATURE INTERVAL
    'degC2K'                    : 1.0e+00,       # degree Celsius (degC) to kelvin (K)
    'degcentigrade2degC'        : 1.0e+00,       # degree centigrade (deg centigrade) to degree Celsius (degC)
    'degF2degC'                 : 5.555556e-01,  # degree Fahrenheit (degF) to degree Celsius (degC)
    'degF2K'                    : 5.555556e-01,  # degree Fahrenheit (degF) to kelvin (K)
    'degR2K'                    : 5.555556e-01,  # degree Rankine (degR) to kelvin (K)
    # TIME
    'd2s'                       : 8.64e+04,      # day (d) to second (s)
    'sidereal2s'                : 8.616409e+04,  # day (sidereal) to second (s)
    'h2s'                       : 3.6e+03,       # hour (h) to second (s)
    'sidereal2s'                : 3.590170e+03,  # hour (sidereal) to second (s)
    'min2s'                     : 6.0e+01,       # minute (min) to second (s)
    'sidereal2s'                : 5.983617e+01,  # minute (sidereal) to second (s)
    'sidereal2s'                : 9.972696e-01,  # second (sidereal) to second (s)
    'shake2s'                   : 1.0e-08,       # shake (shake) to second (s)
    'shake2ns'                  : 1.0e+01,       # shake (shake) to nanosecond (ns)
    'year2s'                    : 3.1536e+07,    # year (365 days) (year) to second (s)
    'siderealyear2s'            : 3.155815e+07,  # year (sidereal ( (sidereal year) to second (s)
    'tropicalyear2s'            : 3.155693e+07,  # year (tropical ( (tropical year) to second (s)
    # TORQUE (see MOMENT OF FORCE)
    # VELOCITY (includes SPEED)
    'ftph2mps'                  : 8.466667e-05,  # foot per hour (ft/h) to meter per second (m/s)
    'ftpmin2mps'                : 5.08e-03,      # foot per minute (ft/min) to meter per second (m/s)
    'ftps2mps'                  : 3.048e-01,     # foot per second (ft/s) to meter per second (m/s)
    'inps2mps'                  : 2.54e-02,      # inch per second (in/s) to meter per second (m/s)
    'kmph2mps'                  : 2.777778e-01,  # kilometer per hour (km/h) to meter per second (m/s)
    'knot2mps'                  : 5.144444e-01,  # nautical mile per hour (knot) to meter per second (m/s)
    'miph2mps'                  : 4.4704e-01,    # mile per hour (mi/h) to meter per second (m/s)
    'miph2kmph'                 : 1.609344e+00,  # mile per hour (mi/h) to kilometer per hour (km/h)
    'mipmin2mps'                : 2.68224e+01,   # mile per minute (mi/min) to meter per second (m/s)
    'mips2mps'                  : 1.609344e+03,  # mile per second (mi/s) to meter per second (m/s)
    'rpmin2radps'               : 1.047198e-01,  # revolution per minute (rpm) (r/min) to radian per second (rad/s)
    'rpmin2radps'               : 1.047198e-01,  # rpm (revolution per minute) (r/min) to radian per second (rad/s)
    # VISCOSITY, DYNAMIC
    'cP2Pas'                    : 1.0e-03,       # centipoise (cP) to pascal second (Pa s)
    'P2Pas'                     : 1.0e-01,       # poise (P) to pascal second (Pa s)
    'poundalspft22Pas'          : 1.488164e+00,  # poundal second per square foot (poundal s / ft2) to pascal second (Pa s)
    'lbfspft22Pas'              : 4.788026e+01,  # pound-force second per square foot (lbf s/ft2) to pascal second (Pa s)
    'lbfspin22Pas'              : 6.894757e+03,  # pound-force second per square inch (lbf s/in2) to pascal second (Pa s)
    'lbpftph2Pas'               : 4.133789e-04,  # pound per foot hour (lb/ft/h) to pascal second (Pa s)
    'lbpftps2Pas'               : 1.488164e+00,  # pound per foot second (lb/ft/s) to pascal second (Pa s)
    'rhe2Pas'                   : 1.0e+01,       # rhe (rhe) to reciprocal pascal second [ (Pa s)-1]
    'slugpftps2Pas'             : 4.788026e+01,  # slug per foot second (slug/ft/s) to pascal second (Pa s)
    # VISCOSITY, KINEMATIC
    'cSt2m2ps'                  : 1.0e-06,       # centistokes (cSt) to meter squared per second (m2/s)
    'ft2ps2m2ps'                : 9.290304e-02,  # square foot per second (ft2/s) to meter squared per second (m2/s)
    'St2m2ps'                   : 1.0e-04,       # stokes (St) to meter squared per second (m2/s)
    # VOLUME (includes CAPACITY)
    'US_srvy_ft_acreft2m3'      : 1.233489e+03,  # acre-foot (U.S. survey foot acre ft) to cubic meter (m3)
    'bbl2m3'                    : 1.589873e-01,  # barrel [for petroleum, 42 gallons (U.S.)] (bbl) to cubic meter (m3)
    'bbl2L'                     : 1.589873e+02,  # barrel [for petroleum, 42 gallons (U.S.)] (bbl) to liter (L)
    'US_bu2m3'                  : 3.523907e-02,  # bushel (U.S. bu) to cubic meter (m3)
    'US_bu2L'                   : 3.523907e+01,  # bushel (U.S. bu) to liter (L)
    'cord2m3'                   : 3.624556e+00,  # cord (128 ft3) (cord) to cubic meter (m3)
    'ft32m3'                    : 2.831685e-02,  # cubic foot (ft3) to cubic meter (m3)
    'in32m3'                    : 1.638706e-05,  # cubic inch (in3) to cubic meter (m3)
    'mi32m3'                    : 4.168182e+09,  # cubic mile (mi3) to cubic meter (m3)
    'yd32m3'                    : 7.645549e-01,  # cubic yard (yd3) to cubic meter (m3)
    'cup2m3'                    : 2.365882e-04,  # cup (cup) to cubic meter (m3)
    'cup2L'                     : 2.365882e-01,  # cup (cup) to liter (L)
    'cup2mL'                    : 2.365882e+02,  # cup (cup) to milliliter (mL)
    'US_floz2m3'                : 2.957353e-05,  # fluid ounce (U.S. fl oz) to cubic meter (m3)
    'US_floz2mL'                : 2.957353e+01,  # fluid ounce (U.S. fl oz) to milliliter (mL)
    'UK_gal2m3'                 : 4.54609e-03,   # gallon (U.K. gal) to cubic meter (m3)
    'UK_gal2L'                  : 4.54609e+00,   # gallon (U.K. gal) to liter (L)
    'US_gal2m3'                 : 3.785412e-03,  # gallon (U.S. gal) to cubic meter (m3)
    'US_gal2L'                  : 3.785412e+00,  # gallon (U.S. gal) to liter (L)
    'UK_gi2m3'                  : 1.420653e-04,  # gill (U.K. gi) to cubic meter (m3)
    'UK_gi2L'                   : 1.420653e-01,  # gill (U.K. gi) to liter (L)
    'US_gi2m3'                  : 1.182941e-04,  # gill (U.S. gi) to cubic meter (m3)
    'US_gi2L'                   : 1.182941e-01,  # gill (U.S. gi) to liter (L)
    'L2m3'                      : 1.0e-03,       # liter (L) to cubic meter (m3)
    'UK_floz2m3'                : 2.841306e-05,  # ounce (U.K. fl oz) to cubic meter (m3)
    'UK_floz2mL'                : 2.841306e+01,  # ounce (U.K. fl oz) to milliliter (mL)
    'US_floz2m3'                : 2.957353e-05,  # ounce (U.S. fl oz) to cubic meter (m3)
    'US_floz2mL'                : 2.957353e+01,  # ounce (U.S. fl oz) to milliliter (mL)
    'US_pk2m3'                  : 8.809768e-03,  # peck (U.S. pk) to cubic meter (m3)
    'US_pk2L'                   : 8.809768e+00,  # peck (U.S. pk) to liter (L)
    'US_drypt2m3'               : 5.506105e-04,  # pint (U.S. dry pt) to cubic meter (m3)
    'US_drypt2L'                : 5.506105e-01,  # pint (U.S. dry pt) to liter (L)
    'US_liqpt2m3'               : 4.731765e-04,  # pint (U.S. liq pt) to cubic meter (m3)
    'US_liqpt2L'                : 4.731765e-01,  # pint (U.S. liq pt) to liter (L)
    'US_dryqt2m3'               : 1.101221e-03,  # quart (U.S. dry qt) to cubic meter (m3)
    'US_dryqt2L'                : 1.101221e+00,  # quart (U.S. dry qt) to liter (L)
    'US_liqqt2m3'               : 9.463529e-04,  # quart (U.S. liq qt) to cubic meter (m3)
    'US_liqqt2L'                : 9.463529e-01,  # quart (U.S. liq qt) to liter (L)
    'st2m3'                     : 1.0e+00,       # stere (st) to cubic meter (m3)
    'Tbsp2m3'                   : 1.478676e-05,  # tablespoon (Tbsp) to cubic meter (m3)
    'Tbsp2mL'                   : 1.478676e+01,  # tablespoon (Tbsp) to milliliter (mL)
    'tsp2m3'                    : 4.928922e-06,  # teaspoon (tsp) to cubic meter (m3)
    'tsp2mL'                    : 4.928922e+00,  # teaspoon (tsp) to milliliter (mL)
    'tonregister2m3'            : 2.831685e+00,  # ton, register (ton, register) to cubic meter (m3)
    # VOLUME DIVIDED BY TIME (includes FLOW)
    'ft3pmin2m3ps'              : 4.719474e-04,  # cubic foot per minute (ft3/min) to cubic meter per second (m3/s)
    'ft3pmin2Lps'               : 4.719474e-01,  # cubic foot per minute (ft3/min) to liter per second (L/s)
    'ft3ps2m3ps'                : 2.831685e-02,  # cubic foot per second (ft3/s) to cubic meter per second (m3/s)
    'in3pmin2m3ps'              : 2.731177e-07,  # cubic inch per minute (in3/min) to cubic meter per second (m3/s)
    'yd3pmin2m3ps'              : 1.274258e-02,  # cubic yard per minute (yd3/min) to cubic meter per second (m3/s)
    'galpd2m3ps'                : 4.381264e-08,  # gallon (U.S.) per day (gal/d) to cubic meter per second (m3/s)
    'galpd2Lps'                 : 4.381264e-05,  # gallon (U.S.) per day (gal/d) to liter per second (L/s)
    'US_galpmin2m3ps'           : 6.309020e-05,  # gallon (U.S. gal/min) to cubic meter per second (m3/s)
    'US_galpmin2Lps'            : 6.309020e-02,  # gallon (U.S. gal/min) to liter per second (L/s)
    # WORK (see ENERGY)
}

def convert(value=0.0, from_unit='', to_unit=''):
    """
    Function to convert a value (float) from one unit (symbol string) to another unit (symbol string).
    The conversion factors comes from the `conversion_factors` dictionary where the key is
    the combination of the from unit plus the to unit, and the value is a float of the conversion value.

    Example:
    In  [1]: # Convert 1 mile to x meter
             convert(1, 'mi', 'm')
    Out [1]: 1609.344
    """

    if from_unit == to_unit:
        result = value
    else:
        factor_lookup = from_unit + '2' + to_unit
        reverse_factor_lookup = to_unit + '2' + from_unit

        factor = None
        result = None
        if conversion_factors.has_key(factor_lookup):
            factor = conversion_factors[factor_lookup]
            result = factor * value
        else:
            if conversion_factors.has_key(reverse_factor_lookup):
                factor = 1.0 / conversion_factors[reverse_factor_lookup]
                result = factor * value
            else:
                raise KeyError('This unit conversion is undefined. See `conversion_factors` dictionary for valid conversions.')
    return result
